const TILE_SIDE = 32;
const TILE_WIDTH = TILE_SIDE;
const TILE_HEIGHT = TILE_SIDE;
const HALF_SIDE = 32 / 2;
const WATER_LEVEL = 2;

export { TILE_SIDE, TILE_WIDTH, TILE_HEIGHT, HALF_SIDE, WATER_LEVEL };
