const TILE_SIDE = 32;
const TILE_WIDTH = TILE_SIDE;
const TILE_HEIGHT = TILE_SIDE;
const HALF_SIDE = 32 / 2;
const WATER_LEVEL = 2;
const GAME_WIDTH_TILES = 24;
const GAME_HEIGHT_TILES = 15;
const GAME_HEIGHT = GAME_HEIGHT_TILES * TILE_HEIGHT;
const GAME_WIDTH = GAME_WIDTH_TILES * TILE_WIDTH;

export {
  TILE_SIDE,
  TILE_WIDTH,
  TILE_HEIGHT,
  HALF_SIDE,
  WATER_LEVEL,
  GAME_WIDTH_TILES,
  GAME_HEIGHT_TILES,
  GAME_WIDTH,
  GAME_HEIGHT,
};
